[2024-03-24T08:02:42.507+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:02:39.275611+00:00 [queued]>
[2024-03-24T08:02:42.510+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:02:39.275611+00:00 [queued]>
[2024-03-24T08:02:42.511+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-24T08:02:42.520+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_data_from_web> on 2024-03-24 08:02:39.275611+00:00
[2024-03-24T08:02:42.527+0000] {standard_task_runner.py:60} INFO - Started process 1054 to run task
[2024-03-24T08:02:42.544+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'scrap_load_data_to_postgres', 'extract_data_from_web', 'manual__2024-03-24T08:02:39.275611+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/scrap_elt_.py', '--cfg-path', '/tmp/tmp51ojklnv']
[2024-03-24T08:02:42.550+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask extract_data_from_web
[2024-03-24T08:02:42.590+0000] {task_command.py:423} INFO - Running <TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:02:39.275611+00:00 [running]> on host c112f9517df7
[2024-03-24T08:02:42.646+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scrap_load_data_to_postgres' AIRFLOW_CTX_TASK_ID='extract_data_from_web' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T08:02:39.275611+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-24T08:02:39.275611+00:00'
[2024-03-24T08:02:44.329+0000] {logging_mixin.py:188} INFO - Sukses!
[2024-03-24T08:02:44.397+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scrap_elt_.py", line 51, in extract_data_from_web
    tanggal_obj = datetime.strptime(second_col[7].text.strip(), '%d %b %Y')
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '-' does not match format '%d %b %Y'
[2024-03-24T08:02:44.405+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=scrap_load_data_to_postgres, task_id=extract_data_from_web, execution_date=20240324T080239, start_date=20240324T080242, end_date=20240324T080244
[2024-03-24T08:02:44.420+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task extract_data_from_web (time data '-' does not match format '%d %b %Y'; 1054)
[2024-03-24T08:02:44.457+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-24T08:02:44.511+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
