[2024-03-24T08:45:39.403+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:45:36.660790+00:00 [queued]>
[2024-03-24T08:45:39.407+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:45:36.660790+00:00 [queued]>
[2024-03-24T08:45:39.407+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-24T08:45:39.416+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_data_from_web> on 2024-03-24 08:45:36.660790+00:00
[2024-03-24T08:45:39.420+0000] {standard_task_runner.py:60} INFO - Started process 3334 to run task
[2024-03-24T08:45:39.423+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'scrap_load_data_to_postgres', 'extract_data_from_web', 'manual__2024-03-24T08:45:36.660790+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/scrap_elt_.py', '--cfg-path', '/tmp/tmpgiduijh1']
[2024-03-24T08:45:39.424+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask extract_data_from_web
[2024-03-24T08:45:39.531+0000] {task_command.py:423} INFO - Running <TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:45:36.660790+00:00 [running]> on host c112f9517df7
[2024-03-24T08:45:39.623+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scrap_load_data_to_postgres' AIRFLOW_CTX_TASK_ID='extract_data_from_web' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T08:45:36.660790+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-24T08:45:36.660790+00:00'
[2024-03-24T08:45:40.646+0000] {logging_mixin.py:188} INFO - Sukses!
[2024-03-24T08:45:40.724+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scrap_elt_.py", line 44, in extract_data_from_web
    item_pemain['harga'] = utils.convert_to_billion(harga)
  File "/opt/airflow/dags/helpers/utils.py", line 71, in convert_to_billion
    amount = float(amount_string)
ValueError: could not convert string to float: '1.216.71'
[2024-03-24T08:45:40.729+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=scrap_load_data_to_postgres, task_id=extract_data_from_web, execution_date=20240324T084536, start_date=20240324T084539, end_date=20240324T084540
[2024-03-24T08:45:40.736+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 38 for task extract_data_from_web (could not convert string to float: '1.216.71'; 3334)
[2024-03-24T08:45:40.790+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-24T08:45:40.804+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
