[2024-03-24T08:19:18.662+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:19:16.625635+00:00 [queued]>
[2024-03-24T08:19:18.664+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:19:16.625635+00:00 [queued]>
[2024-03-24T08:19:18.664+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-24T08:19:18.670+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_data_from_web> on 2024-03-24 08:19:16.625635+00:00
[2024-03-24T08:19:18.674+0000] {standard_task_runner.py:60} INFO - Started process 1935 to run task
[2024-03-24T08:19:18.677+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'scrap_load_data_to_postgres', 'extract_data_from_web', 'manual__2024-03-24T08:19:16.625635+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/scrap_elt_.py', '--cfg-path', '/tmp/tmpkmj1pxhr']
[2024-03-24T08:19:18.678+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask extract_data_from_web
[2024-03-24T08:19:18.706+0000] {task_command.py:423} INFO - Running <TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:19:16.625635+00:00 [running]> on host c112f9517df7
[2024-03-24T08:19:18.737+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scrap_load_data_to_postgres' AIRFLOW_CTX_TASK_ID='extract_data_from_web' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T08:19:16.625635+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-24T08:19:16.625635+00:00'
[2024-03-24T08:19:20.596+0000] {logging_mixin.py:188} INFO - Sukses!
[2024-03-24T08:19:20.647+0000] {logging_mixin.py:188} WARNING - --- Logging error ---
[2024-03-24T08:19:20.649+0000] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-03-24T08:19:20.649+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
[2024-03-24T08:19:20.650+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
[2024-03-24T08:19:20.650+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
[2024-03-24T08:19:20.650+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
[2024-03-24T08:19:20.650+0000] {logging_mixin.py:188} WARNING - TypeError: not all arguments converted during string formatting
[2024-03-24T08:19:20.651+0000] {logging_mixin.py:188} WARNING - Call stack:
[2024-03-24T08:19:20.653+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
[2024-03-24T08:19:20.653+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 57, in main
    args.func(args)
[2024-03-24T08:19:20.654+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-03-24T08:19:20.654+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-03-24T08:19:20.655+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 438, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2024-03-24T08:19:20.655+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 216, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2024-03-24T08:19:20.656+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 278, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2024-03-24T08:19:20.657+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-03-24T08:19:20.657+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 393, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2024-03-24T08:19:20.658+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 422, in execute_job
    ret = execute_callable()
[2024-03-24T08:19:20.659+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/local_task_job_runner.py", line 165, in _execute
    self.task_runner.start()
[2024-03-24T08:19:20.659+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 48, in start
    self.process = self._start_by_fork()
[2024-03-24T08:19:20.660+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 100, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2024-03-24T08:19:20.660+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-03-24T08:19:20.661+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-03-24T08:19:20.661+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 438, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2024-03-24T08:19:20.662+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 218, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2024-03-24T08:19:20.662+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 297, in _run_raw_task
    return ti._run_raw_task(
[2024-03-24T08:19:20.663+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-03-24T08:19:20.663+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2360, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2024-03-24T08:19:20.664+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2532, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2024-03-24T08:19:20.664+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2549, in _execute_task
    return _execute_task(self, context, task_orig)
[2024-03-24T08:19:20.665+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
[2024-03-24T08:19:20.665+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
[2024-03-24T08:19:20.666+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
[2024-03-24T08:19:20.667+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2024-03-24T08:19:20.668+0000] {logging_mixin.py:188} WARNING -   File "/opt/airflow/dags/scrap_elt_.py", line 53, in extract_data_from_web
    item_pemain['kontrak'] = (logging.info(kontrak, "ini kontrak"),utils.extract_date(kontrak)) if kontrak == "-" else kontrak
[2024-03-24T08:19:20.668+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 2082, in info
    root.info(msg, *args, **kwargs)
[2024-03-24T08:19:20.668+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
[2024-03-24T08:19:20.668+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
[2024-03-24T08:19:20.669+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
[2024-03-24T08:19:20.669+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
[2024-03-24T08:19:20.669+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
[2024-03-24T08:19:20.669+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_task_handler.py", line 272, in emit
    self.handler.emit(record)
[2024-03-24T08:19:20.669+0000] {logging_mixin.py:188} WARNING - Message: '-'
Arguments: ('ini kontrak',)
[2024-03-24T08:19:20.670+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scrap_elt_.py", line 53, in extract_data_from_web
    item_pemain['kontrak'] = (logging.info(kontrak, "ini kontrak"),utils.extract_date(kontrak)) if kontrak == "-" else kontrak
  File "/opt/airflow/dags/helpers/utils.py", line 52, in extract_date
    bulan_str = bulan_dict.get(tanggal_parts[1], tanggal_parts[1])
IndexError: list index out of range
[2024-03-24T08:19:20.673+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=scrap_load_data_to_postgres, task_id=extract_data_from_web, execution_date=20240324T081916, start_date=20240324T081918, end_date=20240324T081920
[2024-03-24T08:19:20.689+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 20 for task extract_data_from_web (list index out of range; 1935)
[2024-03-24T08:19:20.719+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-24T08:19:20.726+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
