[2024-03-24T22:37:32.519+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrap_load_data_to_postgres.dbt_run_model_1 manual__2024-03-24T22:37:13.066695+00:00 [queued]>
[2024-03-24T22:37:32.542+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrap_load_data_to_postgres.dbt_run_model_1 manual__2024-03-24T22:37:13.066695+00:00 [queued]>
[2024-03-24T22:37:32.543+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-24T22:37:32.578+0000] {taskinstance.py:2217} INFO - Executing <Task(DbtRunOperator): dbt_run_model_1> on 2024-03-24 22:37:13.066695+00:00
[2024-03-24T22:37:32.608+0000] {standard_task_runner.py:60} INFO - Started process 206 to run task
[2024-03-24T22:37:32.626+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'scrap_load_data_to_postgres', 'dbt_run_model_1', 'manual__2024-03-24T22:37:13.066695+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/scrap_elt_.py', '--cfg-path', '/tmp/tmptkhuk55d']
[2024-03-24T22:37:32.640+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask dbt_run_model_1
[2024-03-24T22:37:32.742+0000] {task_command.py:423} INFO - Running <TaskInstance: scrap_load_data_to_postgres.dbt_run_model_1 manual__2024-03-24T22:37:13.066695+00:00 [running]> on host 08d9f6b8f655
[2024-03-24T22:37:32.877+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scrap_load_data_to_postgres' AIRFLOW_CTX_TASK_ID='dbt_run_model_1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T22:37:13.066695+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-24T22:37:13.066695+00:00'
[2024-03-24T22:37:32.883+0000] {dbt_hook.py:117} INFO - dbt run --profiles-dir /opt/airflow/dbt/airflowdbt --select model_1
[2024-03-24T22:37:32.918+0000] {dbt_hook.py:126} INFO - Output:
[2024-03-24T22:37:38.224+0000] {dbt_hook.py:130} INFO - [0m22:37:38  Running with dbt=1.7.10
[2024-03-24T22:37:38.282+0000] {dbt_hook.py:130} INFO - [0m22:37:38  Encountered an error:
[2024-03-24T22:37:38.283+0000] {dbt_hook.py:130} INFO - Runtime Error
[2024-03-24T22:37:38.283+0000] {dbt_hook.py:130} INFO -   Could not find profile named 'airflowdbt'
[2024-03-24T22:37:42.051+0000] {dbt_hook.py:132} INFO - Command exited with return code 2
[2024-03-24T22:37:42.134+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 98, in execute
    self.create_hook().run_cli('run')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2024-03-24T22:37:42.252+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=scrap_load_data_to_postgres, task_id=dbt_run_model_1, execution_date=20240324T223713, start_date=20240324T223732, end_date=20240324T223742
[2024-03-24T22:37:42.369+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task dbt_run_model_1 (dbt command failed; 206)
[2024-03-24T22:37:42.531+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-24T22:37:42.714+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
