[2024-03-24T08:29:19.625+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:29:16.617663+00:00 [queued]>
[2024-03-24T08:29:19.631+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:29:16.617663+00:00 [queued]>
[2024-03-24T08:29:19.631+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-24T08:29:19.642+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_data_from_web> on 2024-03-24 08:29:16.617663+00:00
[2024-03-24T08:29:19.663+0000] {standard_task_runner.py:60} INFO - Started process 2498 to run task
[2024-03-24T08:29:19.676+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'scrap_load_data_to_postgres', 'extract_data_from_web', 'manual__2024-03-24T08:29:16.617663+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/scrap_elt_.py', '--cfg-path', '/tmp/tmpdngf9jyl']
[2024-03-24T08:29:19.681+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask extract_data_from_web
[2024-03-24T08:29:19.726+0000] {task_command.py:423} INFO - Running <TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:29:16.617663+00:00 [running]> on host c112f9517df7
[2024-03-24T08:29:19.778+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scrap_load_data_to_postgres' AIRFLOW_CTX_TASK_ID='extract_data_from_web' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T08:29:16.617663+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-24T08:29:16.617663+00:00'
[2024-03-24T08:29:21.521+0000] {logging_mixin.py:188} INFO - Sukses!
[2024-03-24T08:29:21.599+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scrap_elt_.py", line 40, in extract_data_from_web
    item_pemain['unique_id'] = df.longstrings.map(hash)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'longstrings'
[2024-03-24T08:29:21.620+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=scrap_load_data_to_postgres, task_id=extract_data_from_web, execution_date=20240324T082916, start_date=20240324T082919, end_date=20240324T082921
[2024-03-24T08:29:21.631+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 30 for task extract_data_from_web ('DataFrame' object has no attribute 'longstrings'; 2498)
[2024-03-24T08:29:21.657+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-24T08:29:21.685+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
